<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.test.rewards.service.CustomerServiceImplTest" tests="3" skipped="0" failures="0" errors="0" timestamp="2023-06-27T23:19:42" hostname="AADS54547314157" time="0.981">
  <properties/>
  <testcase name="getCustomerById()" classname="com.test.rewards.service.CustomerServiceImplTest" time="0.968"/>
  <testcase name="getCustomerByIdShouldThrowNotFoundExceptionIfCustomerNotExistWithTheId()" classname="com.test.rewards.service.CustomerServiceImplTest" time="0.007"/>
  <testcase name="saveCustomer()" classname="com.test.rewards.service.CustomerServiceImplTest" time="0.004"/>
  <system-out><![CDATA[19:19:43.793 [Test worker] WARN com.test.rewards.service.CustomerServiceImpl - Customer does not exist with id - 1.
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
